(* ===================================================================== *)
(*  RDL_ProductSpectrum.v                                                  *)
(*  THE SPECTRAL STRUCTURE OF PRODUCT GRAPHS IS GENERATED BY THE           *)
(*  FACTORS — the Kronecker-sum step of the n-dimensional readout          *)
(*  ladder, entirely over Q (no reals, no limits, no spectral theory:      *)
(*  eigen-structure is carried extensionally by exact Rayleigh pairs,      *)
(*  as in RDL_SpectralCeiling.v).                                          *)
(*                                                                         *)
(*  The Cartesian product of graphs G (nodes 0..nG-1, edges EG) and        *)
(*  H (nodes 0..nH-1, edges EH) has node set {(i,j)} and one edge per      *)
(*  pair (EG-edge, H-node) plus one per pair (G-node, EH-edge).  Its       *)
(*  quadratic form is therefore the edge sum GROUPED BY DIRECTION —        *)
(*  every product edge lies in exactly one group — which is how pgform     *)
(*  below is written; fields on the product are two-index functions.       *)
(*                                                                         *)
(*  CLAIMED HERE (candidate for coqc 8.18.0, axiom-free target):           *)
(*    form_separates      pgform(x (x) y)                                  *)
(*                          == gd_G(x) * |y|^2 + |x|^2 * gd_H(y)   EXACT   *)
(*    norm_separates      pnorm(x (x) y) == |x|^2 * |y|^2          EXACT   *)
(*    rayleigh_additive   exact Rayleigh pairs COMPOSE:                    *)
(*                          (lam, x) on G and (mu, y) on H give            *)
(*                          (lam + mu, x (x) y) on the product —           *)
(*                        the Kronecker-sum law, with no spectral          *)
(*                        theorem invoked                                  *)
(*    pnorm_pos           the composed pair is nondegenerate whenever      *)
(*                        the factors are                                  *)
(*    ceiling_additive    the degree ceilings of RDL_SpectralCeiling.v     *)
(*                        compose additively across factors                *)
(*    gd_const / rayleigh_lifts                                            *)
(*                        the constant field is a null direction of any    *)
(*                        factor, so every exact Rayleigh pair of one      *)
(*                        factor LIFTS UNCHANGED to the product            *)
(*                        (composing with RDL_GraphGrowth.ramp_dilution    *)
(*                        this hands the slow-mode witness to every        *)
(*                        higher-dimensional grid for free)                *)
(*                                                                         *)
(*  Consequence for the ladder: the multi-dimensional spectral             *)
(*  structure of grid graphs is GENERATED, exactly and over Q, by the      *)
(*  one-dimensional factors; only the one-dimensional readout limit        *)
(*  (already available at its own tier) remains per axis.                  *)
(*                                                                         *)
(*  HONESTLY NOT CLAIMED: the CONVERSE spectral statement (that every      *)
(*  Rayleigh value of the product arises as such a sum — classically       *)
(*  true, but it needs a full spectral decomposition we do not invoke);    *)
(*  and any continuum limit (that is the next rung, at Tier-2).            *)
(*                                                                         *)
(*  Pre-verified with exact rational arithmetic (300 random factor         *)
(*  pairs; both separations, additivity, and the constant lift checked     *)
(*  exactly against the literal two-family product edge sum) before        *)
(*  authoring.  Expected: Print Assumptions => Closed.                     *)
(* ===================================================================== *)

Require Coq.Arith.PeanoNat.
Require Coq.Lists.List.
Require Coq.QArith.QArith.
Require Coq.micromega.Lia.
Require Coq.micromega.Lqa.

Module ProductSpectrum.

Import Coq.Lists.List. Import ListNotations.
Import Coq.Arith.PeanoNat.
Import Coq.QArith.QArith.
Import Coq.micromega.Lia.
Import Coq.micromega.Lqa.
Local Open Scope Q_scope.

(* ------------------------------------------------------------------ *)
(* Factor-graph data (shared conventions; self-contained)              *)
(* ------------------------------------------------------------------ *)

Definition Edge : Type := (nat * nat)%type.

Fixpoint qsum (n : nat) (f : nat -> Q) : Q :=
  match n with
  | O => 0
  | S m => qsum m f + f m
  end.

Definition esum (E : list Edge) (g : Edge -> Q) : Q :=
  fold_right (fun e acc => g e + acc) 0 E.

Definition ediff (x : nat -> Q) (e : Edge) : Q := x (fst e) - x (snd e).

(* the diagonal edge form of a factor *)
Definition gd (E : list Edge) (x : nat -> Q) : Q :=
  esum E (fun e => ediff x e * ediff x e).

Definition norm2 (n : nat) (x : nat -> Q) : Q :=
  qsum n (fun i => x i * x i).

(* ------------------------------------------------------------------ *)
(* Product data: two-index fields; the product form written as the     *)
(* edge sum grouped by direction (each product edge in exactly one     *)
(* group); the separable field x (x) y                                 *)
(* ------------------------------------------------------------------ *)

Definition pgform (EG EH : list Edge) (nG nH : nat)
                  (z : nat -> nat -> Q) : Q :=
  qsum nH (fun j => gd EG (fun i => z i j))
  + qsum nG (fun i => gd EH (fun j => z i j)).

Definition pnorm (nG nH : nat) (z : nat -> nat -> Q) : Q :=
  qsum nG (fun i => qsum nH (fun j => z i j * z i j)).

Definition tens (x y : nat -> Q) : nat -> nat -> Q :=
  fun i j => x i * y j.

(* ------------------------------------------------------------------ *)
(* Toolbox                                                             *)
(* ------------------------------------------------------------------ *)

Lemma qsum_ext : forall n (f g : nat -> Q),
  (forall i, (i < n)%nat -> f i == g i) ->
  qsum n f == qsum n g.
Proof.
  induction n as [| m IH]; intros f g H; simpl.
  - reflexivity.
  - rewrite (IH f g); [| intros i Hi; apply H; lia].
    rewrite (H m); [reflexivity | lia].
Qed.

Lemma qsum_scale : forall n (c : Q) (f : nat -> Q),
  qsum n (fun i => c * f i) == c * qsum n f.
Proof.
  induction n as [| m IH]; intros c f; simpl; [ring | rewrite IH; ring].
Qed.

Lemma esum_ext : forall E (f g : Edge -> Q),
  (forall e, In e E -> f e == g e) ->
  esum E f == esum E g.
Proof.
  induction E as [| e r IH]; intros f g H; simpl.
  - reflexivity.
  - rewrite (H e); [| left; reflexivity].
    rewrite (IH f g); [reflexivity | intros e' He'; apply H; right; exact He'].
Qed.

Lemma esum_scale : forall E (c : Q) (g : Edge -> Q),
  esum E (fun e => c * g e) == c * esum E g.
Proof.
  induction E as [| e r IH]; intros c g; simpl; [ring | rewrite IH; ring].
Qed.

Lemma esum_zero : forall E, esum E (fun _ => 0) == 0.
Proof.
  induction E as [| e r IH]; simpl; [reflexivity | rewrite IH; ring].
Qed.

(* scaling a factor field scales its edge form quadratically           *)
Lemma gd_scale_r : forall E (c : Q) (x : nat -> Q),
  gd E (fun i => x i * c) == (c * c) * gd E x.
Proof.
  intros E c x. unfold gd.
  rewrite (esum_ext E
    (fun e => ediff (fun i => x i * c) e * ediff (fun i => x i * c) e)
    (fun e => (c * c) * (ediff x e * ediff x e)));
    [| intros e _; unfold ediff; ring].
  apply esum_scale.
Qed.

Lemma gd_scale_l : forall E (c : Q) (y : nat -> Q),
  gd E (fun j => c * y j) == (c * c) * gd E y.
Proof.
  intros E c y. unfold gd.
  rewrite (esum_ext E
    (fun e => ediff (fun j => c * y j) e * ediff (fun j => c * y j) e)
    (fun e => (c * c) * (ediff y e * ediff y e)));
    [| intros e _; unfold ediff; ring].
  apply esum_scale.
Qed.

(* the constant field is a null direction of every factor form *)
Theorem gd_const : forall E (k : Q), gd E (fun _ => k) == 0.
Proof.
  intros E k. unfold gd.
  rewrite (esum_ext E
    (fun e => ediff (fun _ => k) e * ediff (fun _ => k) e)
    (fun _ => 0));
    [apply esum_zero |].
  intros e _. unfold ediff. ring.
Qed.

(* ------------------------------------------------------------------ *)
(* THE TWO SEPARATIONS                                                 *)
(* ------------------------------------------------------------------ *)

Theorem form_separates : forall EG EH nG nH (x y : nat -> Q),
  pgform EG EH nG nH (tens x y)
  == gd EG x * norm2 nH y + norm2 nG x * gd EH y.
Proof.
  intros EG EH nG nH x y.
  unfold pgform, tens, norm2.
  (* first family: G-edges, one copy per H-node *)
  rewrite (qsum_ext nH (fun j => gd EG (fun i => x i * y j))
                       (fun j => gd EG x * (y j * y j)));
    [| intros j _; rewrite (gd_scale_r EG (y j) x); ring].
  rewrite (qsum_scale nH (gd EG x) (fun j => y j * y j)).
  (* second family: H-edges, one copy per G-node *)
  rewrite (qsum_ext nG (fun i => gd EH (fun j => x i * y j))
                       (fun i => gd EH y * (x i * x i)));
    [| intros i _; rewrite (gd_scale_l EH (x i) y); ring].
  rewrite (qsum_scale nG (gd EH y) (fun i => x i * x i)).
  ring.
Qed.

Theorem norm_separates : forall nG nH (x y : nat -> Q),
  pnorm nG nH (tens x y) == norm2 nG x * norm2 nH y.
Proof.
  intros nG nH x y.
  unfold pnorm, tens, norm2.
  rewrite (qsum_ext nG
    (fun i => qsum nH (fun j => x i * y j * (x i * y j)))
    (fun i => qsum nH (fun j => y j * y j) * (x i * x i))).
  - rewrite (qsum_scale nG (qsum nH (fun j => y j * y j))
                           (fun i => x i * x i)).
    ring.
  - intros i _.
    rewrite (qsum_ext nH (fun j => x i * y j * (x i * y j))
                         (fun j => (x i * x i) * (y j * y j)));
      [| intros j _; ring].
    rewrite (qsum_scale nH (x i * x i) (fun j => y j * y j)).
    ring.
Qed.

(* ------------------------------------------------------------------ *)
(* THE KRONECKER-SUM LAW: exact Rayleigh pairs COMPOSE                 *)
(* ------------------------------------------------------------------ *)

Theorem rayleigh_additive : forall EG EH nG nH (x y : nat -> Q) (lam mu : Q),
  gd EG x == lam * norm2 nG x ->
  gd EH y == mu * norm2 nH y ->
  pgform EG EH nG nH (tens x y)
  == (lam + mu) * pnorm nG nH (tens x y).
Proof.
  intros EG EH nG nH x y lam mu Hx Hy.
  rewrite (form_separates EG EH nG nH x y).
  rewrite (norm_separates nG nH x y).
  rewrite Hx. rewrite Hy. ring.
Qed.

(* nondegeneracy transports to the product *)
Theorem pnorm_pos : forall nG nH (x y : nat -> Q),
  0 < norm2 nG x ->
  0 < norm2 nH y ->
  0 < pnorm nG nH (tens x y).
Proof.
  intros nG nH x y Hx Hy.
  rewrite (norm_separates nG nH x y).
  assert (Hm : 0 * norm2 nH y < norm2 nG x * norm2 nH y)
    by (apply Qmult_lt_compat_r; [exact Hy | exact Hx]).
  lra.
Qed.

(* the degree ceilings of the factors compose additively *)
Theorem ceiling_additive : forall lam mu dG dH : Q,
  lam <= 2 * dG ->
  mu <= 2 * dH ->
  lam + mu <= 2 * (dG + dH).
Proof.
  intros lam mu dG dH H1 H2. lra.
Qed.

(* every exact Rayleigh pair of one factor lifts UNCHANGED to the      *)
(* product along the constant field of the other factor                *)
Theorem rayleigh_lifts : forall EG EH nG nH (x : nat -> Q) (lam : Q),
  gd EG x == lam * norm2 nG x ->
  pgform EG EH nG nH (tens x (fun _ => 1))
  == lam * pnorm nG nH (tens x (fun _ => 1)).
Proof.
  intros EG EH nG nH x lam Hx.
  assert (Hy : gd EH (fun _ => 1) == 0 * norm2 nH (fun _ => 1))
    by (rewrite (gd_const EH 1); ring).
  assert (HT := rayleigh_additive EG EH nG nH x (fun _ => 1) lam 0 Hx Hy).
  lra.
Qed.

(* ================== AXIOM-FREEDOM CHECK ================== *)
Print Assumptions gd_const.
Print Assumptions form_separates.
Print Assumptions norm_separates.
Print Assumptions rayleigh_additive.
Print Assumptions pnorm_pos.
Print Assumptions ceiling_additive.
Print Assumptions rayleigh_lifts.

End ProductSpectrum.
